# Generated by Django 5.0.1 on 2024-01-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_password', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='descriptions',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.CharField(default=3423, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=4343, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(default=43243, max_length=55),
            preserve_default=False,
        ),
    ]
