# Generated by Django 5.0.1 on 2024-01-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_password', '0002_employee_descriptions_employee_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='descriptions',
            field=models.TextField(blank=True, default='Примичании нет', max_length=9999),
        ),
    ]
