# Generated by Django 4.2.4 on 2024-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_password', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='ip_address',
            field=models.CharField(default='YYYY-MM-DDTHH:MM:SS', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='url',
            field=models.CharField(default='YYYY-MM-DDTHH:MM:SS', max_length=255),
            preserve_default=False,
        ),
    ]
