# Generated by Django 4.2.4 on 2024-04-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_password', '0006_alter_employee_ip_address_alter_employee_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ip_address',
            field=models.CharField(blank=True, default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='employee',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
